import type { Muscle } from "@/lib/types";

export const MUSCLES: Muscle[] = [
  { id: "upper_chest", name: "Upper Chest", region: "chest", view: "front", vendorSlug: "chest" },
  {
    id: "mid_chest",
    name: "Chest",
    region: "chest",
    view: "front",
    vendorSlug: "chest",
    isDefault: true,
  },
  { id: "lower_chest", name: "Lower Chest", region: "chest", view: "front", vendorSlug: "chest" },
  {
    id: "front_delts",
    name: "Front Delts",
    region: "shoulders",
    view: "front",
    vendorSlug: "deltoids",
    isDefault: true,
  },
  {
    id: "lateral_delts",
    name: "Lateral Delts",
    region: "shoulders",
    view: "front",
    vendorSlug: "deltoids",
  },
  {
    id: "rear_delts",
    name: "Rear Delts",
    region: "shoulders",
    view: "back",
    vendorSlug: "deltoids",
    isDefault: true,
  },
  {
    id: "lats",
    name: "Lats",
    region: "back",
    view: "back",
    vendorSlug: "upper-back",
    isDefault: true,
  },
  {
    id: "traps",
    name: "Traps",
    region: "back",
    view: "back",
    vendorSlug: "trapezius",
    isDefault: true,
  },
  { id: "rhomboids", name: "Rhomboids", region: "back", view: "back", vendorSlug: "upper-back" },
  {
    id: "spinal_erectors",
    name: "Lower Back",
    region: "back",
    view: "back",
    vendorSlug: "lower-back",
    isDefault: true,
  },
  {
    id: "biceps",
    name: "Biceps",
    region: "arms",
    view: "front",
    vendorSlug: "biceps",
    isDefault: true,
  },
  {
    id: "triceps",
    name: "Triceps",
    region: "arms",
    view: "back",
    vendorSlug: "triceps",
    isDefault: true,
  },
  {
    id: "forearms",
    name: "Forearms",
    region: "arms",
    view: "front",
    vendorSlug: "forearm",
    isDefault: true,
  },
  { id: "abs", name: "Abs", region: "core", view: "front", vendorSlug: "abs", isDefault: true },
  {
    id: "obliques",
    name: "Obliques",
    region: "core",
    view: "front",
    vendorSlug: "obliques",
    isDefault: true,
  },
  {
    id: "glutes",
    name: "Glutes",
    region: "legs",
    view: "back",
    vendorSlug: "gluteal",
    isDefault: true,
  },
  {
    id: "quads",
    name: "Quads",
    region: "legs",
    view: "front",
    vendorSlug: "quadriceps",
    isDefault: true,
  },
  {
    id: "hamstrings",
    name: "Hamstrings",
    region: "legs",
    view: "back",
    vendorSlug: "hamstring",
    isDefault: true,
  },
  {
    id: "calves",
    name: "Calves",
    region: "legs",
    view: "back",
    vendorSlug: "calves",
    isDefault: true,
  },
  {
    id: "adductors",
    name: "Adductors",
    region: "legs",
    view: "front",
    vendorSlug: "adductors",
    isDefault: true,
  },
  { id: "abductors", name: "Abductors", region: "legs", view: "back", vendorSlug: "gluteal" },
  { id: "hip_flexors", name: "Hip Flexors", region: "legs", view: "front" },
  {
    id: "tibialis",
    name: "Tibialis",
    region: "legs",
    view: "front",
    vendorSlug: "tibialis",
    isDefault: true,
  },
];

export const MUSCLES_BY_ID = Object.fromEntries(
  MUSCLES.map((muscle) => [muscle.id, muscle]),
) as Record<Muscle["id"], Muscle>;
