/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BodyMapRouteImport } from './routes/body-map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExerciseSlugRouteImport } from './routes/exercise.$slug'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyMapRoute = BodyMapRouteImport.update({
  id: '/body-map',
  path: '/body-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseSlugRoute = ExerciseSlugRouteImport.update({
  id: '/exercise/$slug',
  path: '/exercise/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body-map': typeof BodyMapRoute
  '/explore': typeof ExploreRoute
  '/exercise/$slug': typeof ExerciseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body-map': typeof BodyMapRoute
  '/explore': typeof ExploreRoute
  '/exercise/$slug': typeof ExerciseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body-map': typeof BodyMapRoute
  '/explore': typeof ExploreRoute
  '/exercise/$slug': typeof ExerciseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/body-map' | '/explore' | '/exercise/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/body-map' | '/explore' | '/exercise/$slug'
  id: '__root__' | '/' | '/body-map' | '/explore' | '/exercise/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyMapRoute: typeof BodyMapRoute
  ExploreRoute: typeof ExploreRoute
  ExerciseSlugRoute: typeof ExerciseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-map': {
      id: '/body-map'
      path: '/body-map'
      fullPath: '/body-map'
      preLoaderRoute: typeof BodyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$slug': {
      id: '/exercise/$slug'
      path: '/exercise/$slug'
      fullPath: '/exercise/$slug'
      preLoaderRoute: typeof ExerciseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyMapRoute: BodyMapRoute,
  ExploreRoute: ExploreRoute,
  ExerciseSlugRoute: ExerciseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
